version: "3.8"

services:
  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: htn-challenge
      # So you don"t have to use root, but you can if you like
      MYSQL_USER: user
      # You can use whatever password you like
      MYSQL_PASSWORD: password
      # Password for root access
      MYSQL_ROOT_PASSWORD: password
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - "3307:3306"
    expose:
      # Opens port 3307 on the container
      - "3307"
      # Where our data will be persisteds
    volumes:
      - htn-db:/var/lib/mysql
  api:
    container_name: htn-api
    depends_on:
      - db
    build:
      context: .
      network: host
    ports:
      - "3333:3333"

# Names our volume
volumes:
  htn-db:
