#!/bin/bash

__dirname=$(dirname "$0")

pnpm prisma migrate reset --force --skip-generate

NODE_ENV="testing" node --experimental-specifier-resolution=node --experimental-vm-modules \
    "${__dirname}/../__tests__/node_modules/jest/bin/jest.js" --config "${__dirname}/../jest.config.cjs" "$@"
